version: "3.2"
services:
  app:
    build: ./docker/app
    ports:
      - 8000:8000
    environment:
      DJANGO_SETTINGS_MODULE: "image.settings.docker"
    volumes:
      - type: bind
        source: ./
        target: /home